# Generated by Django 6.0.2 on 2026-04-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tasks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
